scala_test(
  name = "mysql",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/storage",
    "//java/ucl/pdd/storage/mysql",
    "//javatests/ucl/testing",
    "//javatests/ucl/pdd/storage",
    "//3rdparty/jvm/com/github/nscala_time",
  ]
)
