# PDD is a platform for privacy-preserving Web searches collection.
# Copyright (C) 2016-2018 Vincent Primault <v.primault@ucl.ac.uk>
#
# PDD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PDD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PDD.  If not, see <http://www.gnu.org/licenses/>.

workspace(name = "ucl_pdd")

## Download and load the rules bringing Scala support.
# https://github.com/bazelbuild/rules_scala
rules_scala_version = "4be50865a332aef46c46c94b345c320c3353e9e1"
http_archive(
  name = "io_bazel_rules_scala",
  url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
  type = "zip",
  strip_prefix= "rules_scala-%s" % rules_scala_version
)

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories(("2.12.6", {
    "scala_compiler": "3023b07cc02f2b0217b2c04f8e636b396130b3a8544a8dfad498a19c3e57a863",
    "scala_library": "f81d7144f0ce1b8123335b72ba39003c4be2870767aca15dd0888ba3dab65e98",
    "scala_reflect": "ffa70d522fc9f9deec14358aa674e6dd75c9dfa39d4668ef15bb52f002ce99fa"
}))

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

## Download and load the rules bringing Node support.
# https://github.com/bazelbuild/rules_node
rules_node_version = "0.16.1"
http_archive(
  name = "build_bazel_rules_nodejs",
  url = "https://github.com/bazelbuild/rules_nodejs/archive/%s.zip" % rules_node_version,
  type = "zip",
  strip_prefix= "rules_nodejs-%s" % rules_node_version
)

load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")
rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")
node_repositories(package_json = ["//3rdparty:package.json"])

## Load Maven dependencies.
# Dependencies are automatically generated by the `./bin/bazel-deps` script.
load("//3rdparty/jvm:workspace.bzl", "maven_dependencies")
maven_dependencies()

## Download and load the rules bringing Docker support.
# https://github.com/bazelbuild/rules_docker
rules_docker_version = "9527234ef0b5a57bce93be524cb56d7ab1a85ea3"
http_archive(
  name = "io_bazel_rules_docker",
  url = "https://github.com/bazelbuild/rules_docker/archive/%s.zip" % rules_docker_version,
  type = "zip",
  strip_prefix= "rules_docker-%s" % rules_docker_version
)

load("@io_bazel_rules_docker//scala:image.bzl", scala_image_repositories = "repositories")
scala_image_repositories()
