# Copyright 2017-2018 UCL / Vincent Primault <v.primault@ucl.ac.uk>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "ucl_pdd")

## Download and load the rules bringing Scala support.
# https://github.com/bazelbuild/rules_scala
rules_scala_version = "827124ad15cfc9da87506de989f6ef2ba70ec0c6"
http_archive(
  name = "io_bazel_rules_scala",
  url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
  type = "zip",
  strip_prefix= "rules_scala-%s" % rules_scala_version
)

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

## Download and load the rules bringing Node support.
# https://github.com/bazelbuild/rules_node
rules_node_version = "8c11abc21a96a5305004307e3d98f1d05985ac75"
http_archive(
  name = "build_bazel_rules_nodejs",
  url = "https://github.com/bazelbuild/rules_nodejs/archive/%s.zip" % rules_node_version,
  type = "zip",
  strip_prefix= "rules_nodejs-%s" % rules_node_version
)

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories")
node_repositories(package_json = ["//3rdparty:package.json"])

## Load Maven dependencies.
# Dependencies are automatically generated by the `./bin/bazel-deps` script.
load("//3rdparty/jvm:workspace.bzl", "maven_dependencies")
maven_dependencies()

## Download and load the rules bringing Docker support.
# https://github.com/bazelbuild/rules_docker
rules_docker_version = "452878d665648ada0aaf816931611fdd9c683a97"
http_archive(
  name = "io_bazel_rules_docker",
  url = "https://github.com/bazelbuild/rules_docker/archive/%s.zip" % rules_docker_version,
  type = "zip",
  strip_prefix= "rules_docker-%s" % rules_docker_version
)

load("@io_bazel_rules_docker//scala:image.bzl", scala_image_repositories = "repositories")
scala_image_repositories()
