package(default_visibility = ["//visibility:public"])

scala_library(
  name = "jackson",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/api",
    "//3rdparty/jvm/com/twitter:finatra_jackson",
  ],
)
