package(default_visibility = ["//javatests/ucl/pdd/storage:__subpackages__"])

scala_test(
  name = "storage",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/api",
    "//java/ucl/pdd/storage",
    "//javatests/ucl/testing",
    "//3rdparty/jvm/com/github/nscala_time",
  ]
)
