package(default_visibility = ["//visibility:public"])

scala_library(
    name = "install",
    srcs = glob(["*.scala"]),
    deps = [
        "//java/ucl/pdd/storage",
        "//java/ucl/pdd/storage/memory",
        "//java/ucl/pdd/storage/mysql",
        "//3rdparty/jvm/com/twitter:inject_core",
    ]
)
