package(default_visibility = ["//visibility:public"])

scala_library(
  name = "strategy",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/api",
    "//java/ucl/pdd/storage",
    "//3rdparty/jvm/com/github/nscala_time",
  ],
)
