package(default_visibility = ["//javatests:__subpackages__"])

scala_library(
  name = "testing",
  srcs = glob(["*.scala"]),
  deps = [
    "//3rdparty/jvm/ch/qos/logback:logback_classic",
    "@scalatest//jar:jar",
  ]
)
