package(default_visibility = ["//visibility:public"])

scala_library(
  name = "storage",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/api",
    "//3rdparty/jvm/com/twitter:util_core",
    "//3rdparty/jvm/com/google/guava",
  ],
  exports = [
    "//3rdparty/jvm/com/google/guava",
  ]
)
