package(default_visibility = ["//javatests:__subpackages__"])

scala_library(
    name = "inject",
    srcs = glob(["*.scala"]),
    deps = [
        "//3rdparty/jvm/com/twitter:inject_core",
    ],
)
