package(default_visibility = ["//visibility:public"])

scala_library(
  name = "memory",
  srcs = glob(["*.scala"]),
  deps = [
    "//java/ucl/pdd/api",
    "//java/ucl/pdd/storage",
    "//3rdparty/jvm/com/twitter:util_core",
  ]
)
