scala_test(
  name = "memory",
  srcs = glob(["*.scala"]),
  size = "small",
  deps = [
    "//java/ucl/pdd/storage",
    "//java/ucl/pdd/storage/memory",
    "//javatests/ucl/testing",
    "//javatests/ucl/pdd/storage",
    "//3rdparty/jvm/com/github/nscala_time",
  ]
)
